### ISSUE TITLE
Add a Photo, news removePost removes Photo

### ISSUE THREAD

**Issue by laurenyew** [w7cook/OpenBook#231] opened 2012-04-26 18:18 UTC
Try this:
Upload a photo in My Photos page and then go to the news page. 
click on the removePost button for the news post for the new photo.
Go back to the My Photos page. The photo you added is gone.

**Comment by jtessler** [comment] 2012-04-26 19:22
Ah, I've noticed this before. Looking at the implementation for the timeline, that's basically working as intended. The post on the news page IS the photo uploaded. I'll reassign this to whomever is in charge of timeline.

We should rethink the timeline "removal" as simply "hiding" the post, but not deleting the corresponding content.

**Comment by ProCynic** [comment] 2012-04-26 19:24
exactly.  Photo extends Post for some reason and clicking remove post
removes the post from the database.
-Geoffrey Parker

On Thu, Apr 26, 2012 at 1:18 PM, Lauren Yew <
reply@reply.github.com

**Comment by ProCynic** [comment] 2012-04-26 19:28
If you just hide the thing, it'll still be there when you next reload the page and it shows you all your posts.  The real solution is to have Photo extend Commentable directly.

**Comment by amshali** [comment] 2012-04-26 19:36
Right, that would be better. Then we need to be able to post photo to "Wall". What is a photo post really? It's merely a link to the photo in the post content.

**Closed as completed** 2012-05-03 02:21 UTC
